# Generated by Django 3.1.13 on 2021-11-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnl', '0004_displacement_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displacement',
            old_name='datetime',
            new_name='created_date',
        ),
    ]
