# Generated by Django 3.1.13 on 2021-11-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnl', '0005_auto_20211117_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='displacement',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='displacement',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
