# Generated by Django 3.1.13 on 2021-11-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnl', '0008_luckyday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LuckyDay',
        ),
    ]
