# Generated by Django 3.1.13 on 2021-11-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnl', '0010_luckyday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Displacement',
        ),
    ]
