# Generated by Django 3.1.13 on 2021-11-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnl', '0012_notepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepost',
            name='is_good_day',
            field=models.CharField(choices=[('1', 'Best'), ('2', 'Great'), ('3', 'Good'), ('4', 'Neutral'), ('5', 'Not OK'), ('6', 'Bad'), ('7', 'Worst')], max_length=1),
        ),
    ]
